server:
  port: 9900
spring:
  application:
    name: problem-spring-web-resource-server
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:9904/oauth/token
      user-authorization-uri: http://localhost:9904/oauth/authorize
    resource:
      token-info-uri: http://localhost:9904/oauth/check_token
    authorization:
      check-token-access: http://localhost:9904/oauth/check_token
logging:
  level:
    ROOT: INFO
    org.apache: INFO
    sun: INFO
    com.alibaba: INFO
    org.springframework.security: DEBUG
